onlinemissingvehical/Areas/Admin/Controllers/StatusController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using onlinemissingvehical.Data;
using onlinemissingvehical.Models;
using System.Linq;
using System.Net.Mail;
using System.Net;
using System.Security.Claims;

namespace onlinemissingvehical.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class StatusController : Controller
    {
        private readonly ApplicationDbContext _context;

        public StatusController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var missingVehicles = await _context.MissingVehicles
                .Include(m => m.User)
                .Where(m => !_context.StatusUpdates
                                .Where(s => s.Status == "Recovered")
                                .Select(s => s.MissingVehicleId)
                                .Contains(m.Id))
                .ToListAsync();
            return View(missingVehicles);
        }


        public IActionResult Create(int id)
        {
            var missingVehicle = _context.MissingVehicles.Find(id);
            if (missingVehicle == null)
            {
                return NotFound();
            }

            var statusUpdate = new StatusUpdate
            {
                MissingVehicleId = missingVehicle.Id,
                MissingVehicle = missingVehicle
            };

            return View(statusUpdate);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(StatusUpdate statusUpdate)
        {
            if (ModelState.IsValid)
            {
                var existingStatusUpdate = _context.StatusUpdates.FirstOrDefault(s => s.MissingVehicleId == statusUpdate.MissingVehicleId);

                if (existingStatusUpdate != null)
                {
                    existingStatusUpdate.Status = statusUpdate.Status;
                    _context.StatusUpdates.Update(existingStatusUpdate);
                }
                else
                {
                    statusUpdate.Id = 0;
                    _context.StatusUpdates.Add(statusUpdate);
                }

                _context.SaveChanges();
                var userId = _context.MissingVehicles
                                    .Where(m => m.Id == statusUpdate.MissingVehicleId)
                                    .Select(m => m.UserId)
                                    .FirstOrDefault();
                var existingSubscription = _context.Subscriptions.FirstOrDefault(s => s.UserId == userId);

                if (existingSubscription != null)
                {
                    try
                    {
                        // SMTP server configuration
                        string smtpServer = "smtp-mail.outlook.com";
                        int smtpPort = 587;
                        string smtpUsername = "thakurvishaljamwal@outlook.com";
                        string smtpPassword = "Vishal@2106";

                        // Fetch license plate number of the missing vehicle
                        var licensePlateNumber = _context.MissingVehicles
                                                    .Where(m => m.Id == statusUpdate.MissingVehicleId)
                                                    .Select(m => m.LicensePlateNumber)
                                                    .FirstOrDefault();

                        // Create the email message
                        MailMessage mail = new MailMessage();
                        mail.From = new MailAddress(smtpUsername);
                        mail.To.Add("thakurvishaljamwal@gmail.com");
                        mail.Subject = "Complaint Status";

                        // Set email body based on the selected status and include license plate number
                        string status = statusUpdate.Status;
                        switch (status)
                        {
                            case "Pending":
                                mail.Body = $"Your complaint for vehicle with license plate number {licensePlateNumber} is pending.We can find it as soon as possible.";
                                break;
                            case "Processing":
                                mail.Body = $"Your complaint for vehicle with license plate number {licensePlateNumber} is under processing.We can find it as soon as possible.";
                                break;
                            case "Recovered":
                                mail.Body = $"Your Vehicle with license plate number {licensePlateNumber} has been recovered. Your vehicle will be delivered to your address shortly.";
                                break;
                            default:
                                mail.Body = "Your complaint status is unknown.";
                                break;
                        }

                        // SMTP client configuration and sending email
                        SmtpClient smtpClient = new SmtpClient(smtpServer, smtpPort);
                        smtpClient.Credentials = new NetworkCredential(smtpUsername, smtpPassword);
                        smtpClient.EnableSsl = true;
                        smtpClient.Send(mail);

                        ViewBag.Message = "Email sent successfully!";
                    }
                    catch (Exception ex)
                    {
                        ViewBag.Error = "An error occurred: " + ex.Message;
                    }
                }

                return RedirectToAction("Index", "Home", new { area = "Customer" });
            }
            return View(statusUpdate);
        }


    }
}

onlinemissingvehical/Areas/Customer/Controllers/SubscriptionController.cs
using Microsoft.AspNetCore.Mvc;
using onlinemissingvehical.Data;
using onlinemissingvehical.Models;
using System.Linq;
using System.Net.Mail;
using System.Net;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;

namespace onlinemissingvehical.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class SubscriptionController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SubscriptionController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var subscriptions = _context.Subscriptions
                .Include(s => s.User)
                .ToList();

            return View(subscriptions);
        }

        public IActionResult Subscribe()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var existingSubscription = _context.Subscriptions.FirstOrDefault(s => s.UserId == userId);
            if (existingSubscription != null)
            {
                ViewBag.Message = "You are already subscribed.";
                return View();
            }

            var user = _context.Users.FirstOrDefault(u => u.Id == userId);

            var subscription = new Subscription
            {
                UserId = userId,
                User = (ApplicationUser)user,
                SubscriptionPrice = 200
            };

            return View(subscription);
        }

        [HttpPost]
        public IActionResult Subscribe(Subscription subscription)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var existingSubscription = _context.Subscriptions.FirstOrDefault(s => s.UserId == userId);
            if (existingSubscription != null)
            {
                ViewBag.Message = "You are already subscribed.";
                return View();
            }
            subscription.UserId = userId;
            _context.Subscriptions.Add(subscription);
            _context.SaveChanges();
            try
            {
              
                string smtpServer = "smtp-mail.outlook.com";
                int smtpPort = 587;
                string smtpUsername = "thakurvishaljamwal@outlook.com";
                string smtpPassword = "Vishal@2106";

                MailMessage mail = new MailMessage();
                mail.From = new MailAddress(smtpUsername);
                mail.To.Add("thakurvishaljamwal@gmail.com");
                mail.Subject = "Subscription Confirmation ";
                mail.Body = "Your Subscription Confirm Successfully.";

                SmtpClient smtpClient = new SmtpClient(smtpServer, smtpPort);
                smtpClient.Credentials = new NetworkCredential(smtpUsername, smtpPassword);
                smtpClient.EnableSsl = true;
                smtpClient.Send(mail);

                ViewBag.Message = "Email sent successfully!";
            }
            catch (Exception ex)
            {
                ViewBag.Error = "An error occurred: " + ex.Message;
            }
            return RedirectToAction("Index", "MissingVehical", new { area = "Customer" });
        }
        [HttpPost]
        public IActionResult Delete(int id)
        {
            var subscription = _context.Subscriptions.Find(id);
            if (subscription == null)
            {
                return NotFound();
            }       
            _context.Subscriptions.Remove(subscription);
            _context.SaveChanges();
            try
            {
                string smtpServer = "smtp-mail.outlook.com";
                int smtpPort = 587;
                string smtpUsername = "thakurvishaljamwal@outlook.com";
                string smtpPassword = "Vishal@2106";

                MailMessage mail = new MailMessage();
                mail.From = new MailAddress(smtpUsername);
                mail.To.Add("thakurvishaljamwal@gmail.com");
                mail.Subject = "Subscription Cancellation Notification";
                mail.Body = "Your subscription has been canceled. Please purchase again for further updates about your complaints.";

                SmtpClient smtpClient = new SmtpClient(smtpServer, smtpPort);
                smtpClient.Credentials = new NetworkCredential(smtpUsername, smtpPassword);
                smtpClient.EnableSsl = true;
                smtpClient.Send(mail);
            }
            catch (Exception ex)
            {
                // Handle email sending failure
                ViewBag.Error = "An error occurred while sending email: " + ex.Message;
            }

            return RedirectToAction(nameof(Index));
        }

    }
}

onlinemissingvehical/Views/Shared/_CreateAndBackToListButton.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-info form-control">save</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">Back To List</a>
    </div>
</div>

onlinemissingvehical/Views/Shared/_EditAndBackToListButton.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-info form-control">Update</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">Back To List</a>
    </div>
</div>

onlinemissingvehical/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - onlinemissingvehical</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/onlinemissingvehical.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="https://upload.wikimedia.org/wikipedia/commons/9/9f/Avast_Anti-Theft_logo.png?20161021114333" alt="Logo" height="30" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                        }
                        @if (User.IsInRole(SD.Role_Admin))
                        {                           
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="Admin" asp-controller="Status" asp-action="Index">Complaints</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="customer" asp-controller="Subscription" asp-action="Index">SubScription Details</a>
                            </li>
                        }
                        @if (User.IsInRole(SD.Role_User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="customer" asp-controller="MissingVehical" asp-action="Index">Add Complaint</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="customer" asp-controller="Subscription" asp-action="Subscribe">SubScription</a>
                            </li>
                        }
                        
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - onlinemissingvehical - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>